package com.example.demo.entities;
// Generated Oct 21, 2019, 3:21:12 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditDetails generated by hbm2java
 */
@Entity
@Table(name = "credit_details", catalog = "projectsem_4")
public class CreditDetails implements java.io.Serializable {

	private Integer id;
	private Invoice invoice;
	private int creditId;
	private Date issuedDate;
	private int appliedAmount;
	private Date dueDate;

	public CreditDetails() {
	}

	public CreditDetails(Invoice invoice, int creditId, Date issuedDate, int appliedAmount, Date dueDate) {
		this.invoice = invoice;
		this.creditId = creditId;
		this.issuedDate = issuedDate;
		this.appliedAmount = appliedAmount;
		this.dueDate = dueDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id", nullable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@Column(name = "credit_id", nullable = false)
	public int getCreditId() {
		return this.creditId;
	}

	public void setCreditId(int creditId) {
		this.creditId = creditId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "issued_date", nullable = false, length = 10)
	public Date getIssuedDate() {
		return this.issuedDate;
	}

	public void setIssuedDate(Date issuedDate) {
		this.issuedDate = issuedDate;
	}

	@Column(name = "applied_amount", nullable = false)
	public int getAppliedAmount() {
		return this.appliedAmount;
	}

	public void setAppliedAmount(int appliedAmount) {
		this.appliedAmount = appliedAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", nullable = false, length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

}
