package com.example.demo.entities;
// Generated Oct 21, 2019, 3:21:12 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Factory generated by hbm2java
 */
@Entity
@Table(name = "factory", catalog = "projectsem_4")
public class Factory implements java.io.Serializable {

	private Integer id;
	private String name;
	private String location;
	private Set<RejectionDetails> rejectionDetailses = new HashSet<RejectionDetails>(0);

	public Factory() {
	}

	public Factory(String name, String location) {
		this.name = name;
		this.location = location;
	}

	public Factory(String name, String location, Set<RejectionDetails> rejectionDetailses) {
		this.name = name;
		this.location = location;
		this.rejectionDetailses = rejectionDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", nullable = false, length = 250)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factory")
	public Set<RejectionDetails> getRejectionDetailses() {
		return this.rejectionDetailses;
	}

	public void setRejectionDetailses(Set<RejectionDetails> rejectionDetailses) {
		this.rejectionDetailses = rejectionDetailses;
	}

}
