package com.example.demo.entities;
// Generated Oct 21, 2019, 3:21:12 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "projectsem_4")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private PucharseOrder pucharseOrder;
	private boolean status;
	private Date created;
	private double total;
	private Set<CreditDetails> creditDetailses = new HashSet<CreditDetails>(0);
	private Set<Rejection> rejections = new HashSet<Rejection>(0);
	private Set<RejectionDetails> rejectionDetailses = new HashSet<RejectionDetails>(0);
	private Set<InvoiceDetails> invoiceDetailses = new HashSet<InvoiceDetails>(0);

	public Invoice() {
	}

	public Invoice(PucharseOrder pucharseOrder, boolean status, Date created, double total) {
		this.pucharseOrder = pucharseOrder;
		this.status = status;
		this.created = created;
		this.total = total;
	}

	public Invoice(PucharseOrder pucharseOrder, boolean status, Date created, double total,
			Set<CreditDetails> creditDetailses, Set<Rejection> rejections, Set<RejectionDetails> rejectionDetailses,
			Set<InvoiceDetails> invoiceDetailses) {
		this.pucharseOrder = pucharseOrder;
		this.status = status;
		this.created = created;
		this.total = total;
		this.creditDetailses = creditDetailses;
		this.rejections = rejections;
		this.rejectionDetailses = rejectionDetailses;
		this.invoiceDetailses = invoiceDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pucharseorder_id", nullable = false)
	public PucharseOrder getPucharseOrder() {
		return this.pucharseOrder;
	}

	public void setPucharseOrder(PucharseOrder pucharseOrder) {
		this.pucharseOrder = pucharseOrder;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "total", nullable = false, precision = 22, scale = 0)
	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<CreditDetails> getCreditDetailses() {
		return this.creditDetailses;
	}

	public void setCreditDetailses(Set<CreditDetails> creditDetailses) {
		this.creditDetailses = creditDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<Rejection> getRejections() {
		return this.rejections;
	}

	public void setRejections(Set<Rejection> rejections) {
		this.rejections = rejections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<RejectionDetails> getRejectionDetailses() {
		return this.rejectionDetailses;
	}

	public void setRejectionDetailses(Set<RejectionDetails> rejectionDetailses) {
		this.rejectionDetailses = rejectionDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<InvoiceDetails> getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set<InvoiceDetails> invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

}
