package com.example.demo.entities;
// Generated Oct 21, 2019, 3:21:12 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "projectsem_4")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String description;
	private String photo;
	private double price;
	private boolean status;
	private Set<PucharseOrder> pucharseOrders = new HashSet<PucharseOrder>(0);
	private Set<RejectionDetails> rejectionDetailses = new HashSet<RejectionDetails>(0);
	private Set<Inventory> inventories = new HashSet<Inventory>(0);

	public Product() {
	}

	public Product(Category category, String name, double price, boolean status) {
		this.category = category;
		this.name = name;
		this.price = price;
		this.status = status;
	}

	public Product(Category category, String name, String description, String photo, double price, boolean status,
			Set<PucharseOrder> pucharseOrders, Set<RejectionDetails> rejectionDetailses, Set<Inventory> inventories) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.photo = photo;
		this.price = price;
		this.status = status;
		this.pucharseOrders = pucharseOrders;
		this.rejectionDetailses = rejectionDetailses;
		this.inventories = inventories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<PucharseOrder> getPucharseOrders() {
		return this.pucharseOrders;
	}

	public void setPucharseOrders(Set<PucharseOrder> pucharseOrders) {
		this.pucharseOrders = pucharseOrders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<RejectionDetails> getRejectionDetailses() {
		return this.rejectionDetailses;
	}

	public void setRejectionDetailses(Set<RejectionDetails> rejectionDetailses) {
		this.rejectionDetailses = rejectionDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

}
