package com.example.demo.entities;
// Generated Oct 21, 2019, 3:21:12 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rejection generated by hbm2java
 */
@Entity
@Table(name = "rejection", catalog = "projectsem_4")
public class Rejection implements java.io.Serializable {

	private Integer id;
	private Invoice invoice;
	private PucharseOrder pucharseOrder;
	private Date created;
	private boolean status;
	private Set<RejectionDetails> rejectionDetailses = new HashSet<RejectionDetails>(0);

	public Rejection() {
	}

	public Rejection(Invoice invoice, PucharseOrder pucharseOrder, Date created, boolean status) {
		this.invoice = invoice;
		this.pucharseOrder = pucharseOrder;
		this.created = created;
		this.status = status;
	}

	public Rejection(Invoice invoice, PucharseOrder pucharseOrder, Date created, boolean status,
			Set<RejectionDetails> rejectionDetailses) {
		this.invoice = invoice;
		this.pucharseOrder = pucharseOrder;
		this.created = created;
		this.status = status;
		this.rejectionDetailses = rejectionDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_id", nullable = false)
	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pucharseorder_id", nullable = false)
	public PucharseOrder getPucharseOrder() {
		return this.pucharseOrder;
	}

	public void setPucharseOrder(PucharseOrder pucharseOrder) {
		this.pucharseOrder = pucharseOrder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rejection")
	public Set<RejectionDetails> getRejectionDetailses() {
		return this.rejectionDetailses;
	}

	public void setRejectionDetailses(Set<RejectionDetails> rejectionDetailses) {
		this.rejectionDetailses = rejectionDetailses;
	}

}
